### ISSUE TITLE
Modifiications to make outer UI match Scrimba colors

### ISSUE THREAD

**Issue by aadilayub** [drkcode/scrimba-dark-theme#1]
Hi! Thanks for developing this theme. I installed it a few days ago but felt the editor didn't really match scrimba's colors. It felt like I was using normal VScode but with scrimba syntax highlighting.

I made these edits in `settings.json` to make it match the website a bit more:

```
"workbench.colorCustomizations": {
    "[Scrimba Dark Theme Editing]": {
        "statusBar.background": "#4a5667",
        "tab.activeBackground": "#1f1e1c",
        "tab.inactiveBackground": "#272723",
        "titleBar.activeBackground": "#4a5667",
        "editorGroupHeader.tabsBackground": "#272723",
        "activityBar.background": "#4a5667",
        "activityBar.activeBackground": "#4a5667",
        "activityBar.activeBorder": "#334155",
        "sideBar.background": "#272723",
        "sideBarSectionHeader.background": "#272723",
    }
}
```

![image](https://user-images.githubusercontent.com/31581044/160559911-9c7e3411-7ae4-4c85-a660-627f93d8116f.png)

I don't know how to create a VScode theme myself, so I'm adding these modifications here in lieu of a pull request if you would like to incorporate them into your theme.

**Comment by drkcode** [comment]
Hey. Thank you for your contribution. I will apply your modifications to it.
